"""
Launch-screen images for the installed app (PLAN.md S-1 / S-2).

Every launch screen is the same picture: #141310 with the white W in the
middle, 120 CSS px wide. It is all Android can draw from the manifest
(background_color + icon), so iPhone and the page itself show exactly that
too and the three hand over without a jump.

Writes:
  public/brand/launch-mark.png   the W on a transparent ground (inlined into
                                 index.html's launch screen)
  public/splash/*.png            one iOS startup image per screen size
  index.html                     the <link rel="apple-touch-startup-image">
                                 block between the LAUNCH-IMAGES markers

Run from personal-wealth-os/:  python scripts/generate-launch-images.py
Needs Pillow. Re-run whenever the icon changes or Apple adds a screen size.
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ICON = ROOT / "public/icons/icon-512-maskable.png"
MARK_OUT = ROOT / "public/brand/launch-mark.png"
SPLASH_DIR = ROOT / "public/splash"
INDEX = ROOT / "index.html"

GROUND = (20, 19, 16)  # #141310, manifest background_color
MARK_CSS_WIDTH = 120  # must match #launch img in index.html

# (label, CSS width, CSS height, device pixel ratio) in portrait.
IPHONES = [
    ("iPhone 16/17 Pro Max", 440, 956, 3),
    ("iPhone Air", 420, 912, 3),
    ("iPhone 16/17 Pro, 17", 402, 874, 3),
    ("iPhone 14 Pro Max, 15/16 Plus, 15 Pro Max", 430, 932, 3),
    ("iPhone 14 Pro, 15, 15 Pro, 16", 393, 852, 3),
    ("iPhone 12/13 Pro Max, 14 Plus", 428, 926, 3),
    ("iPhone 12, 12 Pro, 13, 13 Pro, 14, 16e", 390, 844, 3),
    ("iPhone X, XS, 11 Pro, 12/13 mini", 375, 812, 3),
    ("iPhone XS Max, 11 Pro Max", 414, 896, 3),
    ("iPhone XR, 11", 414, 896, 2),
    ("iPhone 6/7/8 Plus", 414, 736, 3),
    ("iPhone 6/7/8, SE 2/3", 375, 667, 2),
    ("iPhone SE (1st)", 320, 568, 2),
]
IPADS = [
    ("iPad Pro 13 (M4)", 1032, 1376, 2),
    ("iPad Pro 12.9, Air 13 (M2)", 1024, 1366, 2),
    ("iPad Pro 11 (M4)", 834, 1210, 2),
    ("iPad Pro 11, Air 11 (M2)", 834, 1194, 2),
    ("iPad Air 4/5, iPad 10", 820, 1180, 2),
    ("iPad Pro 10.5, Air 3", 834, 1112, 2),
    ("iPad 7/8/9", 810, 1080, 2),
    ("iPad mini 6/7", 744, 1133, 2),
    ("iPad 5/6, mini 4/5, Air 2", 768, 1024, 2),
]


def transparent_mark() -> Image.Image:
    """The icon's white W with its ground made transparent, cropped tight.

    Coverage is recovered from how far each pixel moved from the ground
    toward white, so the anti-aliased edge survives.
    """
    src = Image.open(ICON).convert("RGB")
    out = Image.new("RGBA", src.size)
    px, po = src.load(), out.load()
    for y in range(src.height):
        for x in range(src.width):
            r, g, b = px[x, y]
            a = ((r - GROUND[0]) / (255 - GROUND[0]) + (g - GROUND[1]) / (255 - GROUND[1]) + (b - GROUND[2]) / (255 - GROUND[2])) / 3
            po[x, y] = (255, 255, 255, round(max(0.0, min(1.0, a)) * 255))
    return out.crop(out.getbbox())


def scaled(mark: Image.Image, width: int) -> Image.Image:
    return mark.resize((width, round(mark.height * width / mark.width)), Image.LANCZOS)


def splash(mark: Image.Image, w: int, h: int, dpr: int) -> Image.Image:
    canvas = Image.new("RGB", (w * dpr, h * dpr), GROUND)
    m = scaled(mark, MARK_CSS_WIDTH * dpr)
    canvas.paste(m, ((canvas.width - m.width) // 2, (canvas.height - m.height) // 2), m)
    return canvas


def main() -> None:
    mark = transparent_mark()
    scaled(mark, MARK_CSS_WIDTH * 2).save(MARK_OUT, optimize=True)

    SPLASH_DIR.mkdir(parents=True, exist_ok=True)
    for old in SPLASH_DIR.glob("apple-splash-*.png"):
        old.unlink()

    links = []
    seen = set()
    screens = [(label, w, h, dpr, "portrait") for label, w, h, dpr in IPHONES]
    for label, w, h, dpr in IPADS:
        screens.append((label, w, h, dpr, "portrait"))
        screens.append((label, h, w, dpr, "landscape"))
    for label, w, h, dpr, orientation in screens:
        name = f"apple-splash-{w * dpr}x{h * dpr}.png"
        if name not in seen:
            splash(mark, w, h, dpr).save(SPLASH_DIR / name, optimize=True)
            seen.add(name)
        # Media features are in portrait terms: device-width is the short side.
        short, long = min(w, h), max(w, h)
        links.append(
            f'    <link rel="apple-touch-startup-image" href="/splash/{name}" media="screen and (device-width: {short}px) and '
            f'(device-height: {long}px) and (-webkit-device-pixel-ratio: {dpr}) and (orientation: {orientation})" /><!-- {label} -->'
        )

    start, end = "    <!-- LAUNCH-IMAGES:START", "    <!-- LAUNCH-IMAGES:END -->"
    html = INDEX.read_text(encoding="utf-8")
    block = (
        "    <!-- LAUNCH-IMAGES:START (generated by scripts/generate-launch-images.py; do not edit by hand) -->\n"
        + "\n".join(links)
        + "\n" + end
    )
    if start in html:
        html = html[: html.index(start)] + block + html[html.index(end) + len(end):]
    else:
        anchor = '    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />'
        html = html.replace(anchor, anchor + "\n" + block, 1)
    INDEX.write_text(html, encoding="utf-8")
    print(f"{len(seen)} images, {len(links)} links, mark {MARK_OUT.name}")


if __name__ == "__main__":
    main()
